import Vue from 'vue'
import { MLInstaller, MLCreate, MLanguage } from 'vue-multilanguage'

Vue.use(MLInstaller)

export default new MLCreate({
    initial: 'ru',
    save: process.env.NODE_ENV === 'production',
    languages: [
        new MLanguage('ru').create({
            callBack: 'Заказать&nbsp;звонок',
            title: 'Лицензирование строительной <br>деятельности в Казахстане',
            subtitle: 'Ответьте на&nbsp;наши вопросы и&nbsp;получите точный расчёт наших&nbsp;услуг',
            btn_home: 'Получить расчёт и&nbsp;подарок',
            btn_send: 'Оставить заявку',
            site_link: 'Перейти на сайт',
            header_step: 'Вопрос {0}',
            header_step_cont: 'Контакты',
            header_thank: 'Спасибо',
            header_title_1: 'Какая лицензия вам необходима?',
            header_title_2: 'Информация о заявителе',
            
            header_title_3: 'Наличие подтверждённого опыта работ',
            header_title_4: 'Наличие оборотов по расчетному счёту',
            header_title_5: 'Наличие НДС',
            header_title_6: 'Наличие ПКО Самрук-Казына',
            header_title_7: 'Наличие ПКО Государственные закупки',
            header_title_8: 'Заказать и получить скидку 50&nbsp;000 тенге при&nbsp;покупке в&nbsp;течении 7&nbsp;дней',
            label_1_1: 'Тип лицензии',
            label_1_2: 'Тип категории',
            opt_1_s: 'Cтроительная',
            opt_1_p: 'Проектная',
            opt_1_1c: 'Первой категории',
            opt_1_2c: 'Второй категории',
            opt_1_3c: 'Третьей категории',
            opt_1_4c: 'Нужна помощь в определении категории',
            opt_2_r: 'Юридическое лицо, резидент Казахстана',
            opt_2_nr: 'Юридическое лицо, резидент другой страны',
            opt_3_yes: 'Есть',
            opt_3_no: 'Нет',
            opt_3_nu: 'Не понял вопрос',
            opt_4_yes: 'Планирую',
            opt_4_no: 'Не планирую',
            opt_4_cons: 'Необходима консультация',
            opt_help_4_s: 'Строительство',
            opt_help_4_p: 'Проектирование',
            opt_help_4_sp: 'Проектирование и строительство',
            opt_5_yes: 'Есть в наличии',
            opt_5_no: 'Нет в наличии',
            opt_5_help: 'Нужна помощь в определении',
            opt_5_3_yes: 'Есть в наличии',
            opt_5_3_help: 'Нужна помощь в определении и аттестации',
            opt_help_5_g: 'Гражданское строительство',
            opt_help_5_p: 'Промышленное строительство',
            label_6_help: 'Опишите ключевые параметры проектируемого или подлежащего строительству объекта',
            opt_5_с_1_1: 'Акты приемки работ государственной комиссией, от 10 экземпляров',
            opt_5_с_1_2: 'Акты выполненных работ по договорам субподряда, от 20 экземпляров',
            opt_5_с_1_3: 'Нужна помощь в определении',
            opt_5_с_2_1: 'Акты приемки работ государственной комиссией, от 5 экземпляров',
            opt_5_с_2_2: 'Акты выполненных работ по договорам субподряда, от 10 экземпляров',
            opt_5_с_2_3: 'Нужна помощь в определении',
            
            opt8_label_1: 'Выберите предпочитаемые способы связи',
            opt8_label_2: 'Введите номер телефона и&nbsp;покупатель свяжется с&nbsp;вами в&nbsp;ближайшее время',
            opt8_1: 'Звонок',
            opt8_2: 'WhatsApp',
            opt8_3: 'СМС',
            alert_phone: 'Некорректно введен телефон',
            alert_text: 'Введите значеине или пропустите данный шаг',
            alert_select: 'Выберите значеине или пропустите данный шаг',
            yes: 'Да',
            no: 'Нет',
            next: 'Далее →',
            final_text: 'Введите номер телефона и&nbsp;получите расчёт&nbsp;на WhatsApp и&nbsp;СМС <br>в&nbsp;течение <span class="mark">5 минут.</span>',
            alarm: 'Оставляя контактную информацию, вы соглашаетесь на обработку персональных данных',
            thanks_subtitle: 'Спасибо!',
            thanks_title: 'Ваша заявка принята',
            thanks_link: 'Скачать файл',
            modal_title: 'Заказать&nbsp;звонок',
            modal_intro: 'Заполните форму и&nbsp;мы свяжемся с&nbsp;вами в&nbsp;течение <span class="mark">5&nbsp;минут.</span>',
            send: 'Отправить',
            title_send: 'Cпасибо, заявка отправлена'
        }),
        new MLanguage('en').create({
            callBack: 'Order a call',
            title: 'Company formation in&nbsp;Kazakhstan',
            subtitle: 'Discover questionnaire and get a&nbsp;detailed cost report and gift from &nbsp;in&nbsp;three simple steps',
            btn_home: 'Get personalized report and&nbsp;gift!',
            btn_send: 'Отправить компанию на продажу',
            site_link: 'Visit website',
            header_step: 'Вопрос {0}',
            header_step_cont: 'Контакты',
            header_thank: 'Спасибо',
            header_title_1: 'Какая лицензия вам необходима?',
            header_title_2_1: 'Информация о заявителе',
            header_title_3: 'Наличие подтверждённого опыта работ',
            header_title_4: 'Наличие оборотов по расчетному счёту',
            header_title_5: 'Наличие НДС',
            header_title_6: 'Наличие ПКО Самрук-Казына',
            header_title_7: 'Наличие ПКО Государственные закупки',
            header_title_8: 'Заказать и получить скидку 50&nbsp;000 тенге при&nbsp;покупке в&nbsp;течении 7&nbsp;дней',
            label_1_1: 'Тип лицензии',
            label_1_2: 'Тип категории',
            opt_1_1_1: 'Cтроительная',
            opt_1_1_2: 'Проектная',
            opt_1_2_1: 'Первой категории',
            opt_1_2_2: 'Второй категории',
            opt_1_2_3: 'Третьей категории',
            opt_1_2_4: 'Нужна помощь в определении категории',
            opt_2_1_1: 'Юридическое лицо, резидент Казахстана',
            opt_2_1_2: 'Юридическое лицо, резидент другой страны',
            opt_2_2_1: '',
            opt_2_2_2: '',
            
            opt8_label_1: 'Выберите предпочитаемые способы связи',
            opt8_label_2: 'Введите номер телефона и&nbsp;покупатель свяжется с&nbsp;вами в&nbsp;ближайшее время',
            opt8_1: 'Звонок',
            opt8_2: 'WhatsApp',
            opt8_3: 'СМС',
            alert_bin: 'Некорректный БИН',
            alert_phone: 'Некорректно введен телефон',
            alert_text: 'Введите значеине или пропустите данный шаг',
            alert_select: 'Выберите значеине или пропустите данный шаг',
            yes: 'Yes',
            no: 'No',
            next: 'Next →',
            final_text: 'Please enter your phone number and get a&nbsp;quote on&nbsp;WhatsApp or&nbsp;SMS within <span class="mark">5 minutes.</span>',
            alarm: 'By providing us with your contact details you agree for&nbsp;processing of&nbsp;your personal data',
            thanks_subtitle: 'Thank you!',
            thanks_title: 'Your application is accepted',
            thanks_link: 'Download',
            modal_intro: 'Fill out the form and&nbsp;we will contact you within <span class="mark">5&nbsp;minutes.</span>',
            send: 'Send',
            title_send: 'Thank you, the&nbsp;application has been sent'
        })
    ]
})